# Generated by Django 4.0.3 on 2022-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcommons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem de perfil (Base64)'),
        ),
    ]
